### ISSUE TITLE
Questions about AFT

### ISSUE THREAD

**Issue by wangyuxin87** [WD-Leong/NLP-Attention-Free-Transformer#1]
Thanks for your code. I have two questions:
1. Is there an abvious performance difference between torch_gpt and torch_aft?
2. I find the speed of AFT in this code is similar to the Self-Attention, maybe the local operation in the paper will speed up?

**Comment by WD-Leong** [comment]
> Thanks for your code. I have two questions:
> 
> 1. Is there an abvious performance difference between torch_gpt and torch_aft?
> 2. I find the speed of AFT in this code is similar to the Self-Attention, maybe the local operation in the paper will speed up?

Hello, thank you for your comments. 

On the first question, I did not really run extensive tests so I am unable to comment whether there is an performance difference between the two codes. 

Regarding the second question, I observed faster training time for torch_gpt as compared to torch_aft, I am guessing that this may be due to matrix multiplication operation being more optimized for GPU as compared the cumulative sum operation for longer sequence lengths. The local operation might be able to improve the training time for AFT as you pointed out.

Thank you.
